name: PyTorch Build From Source

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install conda dependencies
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        run: |
          $CONDA/bin/conda env update --file env.yml --name base

      - name: Clone and build PyTorch
        run: |
          git clone https://github.com/pytorch/pytorch.git
          cd pytorch
          git checkout v1.11.0
          git submodule sync
          git submodule update --init --recursive --jobs 0
          export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
          python3 setup.py install
          export PYTHONPATH=$PYTHONPATH:$PWD
          source $HOME/.bashrc

      - name: Test
        run: |
          python3 ${{github.workspace}}/test/pt.py
