name: PyTorch Build From Source

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - uses: actions/checkout@v3

      - uses: Jimver/cuda-toolkit@v0.2.5
        id: cuda-toolkit
        with:
          cuda: "11.2"

      - name: Test CUDA installation
        run: |
          echo "Installed CUDA version is: ${{steps.cuda-toolkit.outputs.cuda}}"
          echo "CUDA install location: ${{steps.cuda-toolkit.outputs.CUDA_PATH}}"
          nvcc -V

      - uses: conda-incubator/setup-miniconda@v2.1.1
        with:
          miniconda-version: "latest"
          mamba-version: "*"
          channels: conda-forge,defaults
          channel-priority: true
          activate-environment: pipeswitch
          environment-file: env.yml
          python-version: 3.8
          auto-activate-base: false

      - name: Test conda installation
        run: |
          conda info
          conda list

      - name: Set environment variables
        run: |
          export MAX_JOBS=$(nproc)
          echo $MAX_JOBS
          export USE_CUDA=1
          echo $USE_CUDA
          export USE_CUDNN=1
          echo $USE_CUDNN
          export CUDA_HOME=${{steps.cuda-toolkit.outputs.CUDA_PATH}}
          echo $CUDA_HOME
          export CUDNN_INCLUDE_DIR=${{$CONDA/envs/pipeswitch/include}}
          echo $CUDNN_INCLUDE_DIR
          export CUDNN_LIB_DIR=${{$CONDA/envs/pipeswitch/lib}}
          echo $CUDNN_LIB_DIR

      - name: Clone and build PyTorch
        run: |
          git clone https://github.com/pytorch/pytorch.git
          cd pytorch
          git checkout v1.11.0
          git submodule sync
          git submodule update --init --recursive --jobs 0
          export CMAKE_PREFIX_PATH=${CONDA_PREFIX:-"$(dirname $(which conda))/../"}
          python3 setup.py install
          export PYTHONPATH=$PYTHONPATH:$PWD
          source $HOME/.bashrc

      - name: Test
        run: |
          python3 ${{github.workspace}}/test/pt.py
